"use client"
import { Footer } from '@/components/footer'
import './globals.css'
import { Inter } from 'next/font/google'
import { ConnectWalletComponent } from '@/components/connectWallet'
import React from 'react'
import { Emitter } from '@/utils/Emitter'
import { useEmitter } from '@/useHooks/useEmitter'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const EmitterContext = React.createContext<Emitter | null>(null);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const emitter = useEmitter()

  return (
    <html lang="en">
      <body className={inter.className}>
        <EmitterContext.Provider value={emitter}>
          <ConnectWalletComponent />
          {children}
          <Footer />
        </EmitterContext.Provider>
      </body>
    </html>
  )
}
